import { Injectable } from '@nestjs/common';
import { TaskRepository } from '../../shared/database/repositories/task.repository';
import { RewardEngineService } from '../../reward-engine/reward.service';
import { Earning, EarningStatus } from '../types/earning';

/**
 * Worker ka earning calculate karta hai
 */
@Injectable()
export class EarningCalculator {
    constructor(
        private readonly taskRepo: TaskRepository,
        private readonly rewardEngine: RewardEngineService,
    ) { }

    async calculate(taskId: string, workerId: string): Promise<Earning> {
        const task = await this.taskRepo.findById(taskId);

        if (!task) {
            throw new Error('Task not found');
        }

        // Get reward snapshot or fallback to task.rewardAmount
        const rewardSnapshot = await this.rewardEngine.getSnapshotReward(taskId);
        const rewardAmount = rewardSnapshot?.totalReward ?? Number(task.rewardAmount || 0);

        const earning: Earning = {
            id: null, // Will be generated by database
            workerId,
            taskId,
            amount: rewardAmount,
            type: 'task_completion',
            status: EarningStatus.PENDING,
            metadata: {
                rewardSnapshot,
                taskType: task.taskType,
                completedAt: new Date(),
            },
        };

        return earning;
    }
}
